### ISSUE TITLE
How to setup a hotkey for the "uninstall" action?

### ISSUE THREAD

**Issue by gendalv** [CyberSavvy531/RimWorldMiniaturization#1]
Add a hotkey for it pls.
Also add a mass uninstall order.

**Comment by gendalv** [comment]
figured the lack of hotkey out: it uses same 'P' as "select similar" button, but still would be nice to have its own hotkey in controls and to have mass uninstall order.

**Comment by CyberSavvy531** [comment]
Adding a hotkey is not in the scope of this mod, and while I've never personally felt the need for a hotkey for uninstalling buildings, I am surprised to find it's not a vanilla hotkey. Adding hotkey bindings, I believe, requires knowledge of C# and the RimWorld code libraries, which I am lacking. You may want to direct your question to UnlimitedHugs over the "Allow Tool" mod. I'd be willing to bet it's something he could add easily to his mod, and such a feature would be better suited to his mod than this one.

If you're simply wanting to uninstall multiple buildings at once, though, you can just select the ones you want then click uninstall, and all uninstallable buildings will be marked as such.
